# Generated by Django 4.2.4 on 2023-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expertness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("percentage", models.IntegerField()),
            ],
        ),
    ]
